//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voltiq.Exceptions.Resources;

using System;
using System.Reflection;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
public static class ResourceErrorMessages
{
    private static global::System.Resources.ResourceManager? _resourceManager;

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    public static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            _resourceManager ??= new global::System.Resources.ResourceManager(
                "Voltiq.Exceptions.Resources.ResourceErrorMessages",
                typeof(ResourceErrorMessages).Assembly);

            return _resourceManager;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to O e-mail é obrigatório.
    /// </summary>
    public static string Email_Obrigatorio
        => ResourceManager.GetString(nameof(Email_Obrigatorio))!;

    /// <summary>
    ///   Looks up a localized string similar to '{0}' não é um endereço de e-mail válido.
    /// </summary>
    public static string Email_Invalido
        => ResourceManager.GetString(nameof(Email_Invalido))!;

    /// <summary>
    ///   Looks up a localized string similar to O documento (CPF/CNPJ) é obrigatório.
    /// </summary>
    public static string Documento_Obrigatorio
        => ResourceManager.GetString(nameof(Documento_Obrigatorio))!;

    /// <summary>
    ///   Looks up a localized string similar to O documento deve ser um CPF (11 dígitos) ou CNPJ (14 dígitos) válido.
    /// </summary>
    public static string Documento_FormatoInvalido
        => ResourceManager.GetString(nameof(Documento_FormatoInvalido))!;

    /// <summary>
    ///   Looks up a localized string similar to CPF inválido.
    /// </summary>
    public static string Cpf_Invalido
        => ResourceManager.GetString(nameof(Cpf_Invalido))!;

    /// <summary>
    ///   Looks up a localized string similar to CNPJ inválido.
    /// </summary>
    public static string Cnpj_Invalido
        => ResourceManager.GetString(nameof(Cnpj_Invalido))!;

    /// <summary>
    ///   Looks up a localized string similar to O nome é obrigatório.
    /// </summary>
    public static string Nome_Obrigatorio
        => ResourceManager.GetString(nameof(Nome_Obrigatorio))!;

    /// <summary>
    ///   Looks up a localized string similar to O hash da senha é obrigatório.
    /// </summary>
    public static string HashSenha_Obrigatorio
        => ResourceManager.GetString(nameof(HashSenha_Obrigatorio))!;

    /// <summary>
    ///   Looks up a localized string similar to A entidade '{0}' com a chave '{1}' não foi encontrada.
    /// </summary>
    public static string Entidade_NaoEncontrada
        => ResourceManager.GetString(nameof(Entidade_NaoEncontrada))!;

    // ── Aplicação — Usuário ────────────────────────────────────────────────

    /// <summary>
    ///   Looks up a localized string similar to O nome é obrigatório.
    /// </summary>
    public static string Usuario_Nome_Obrigatorio
        => ResourceManager.GetString(nameof(Usuario_Nome_Obrigatorio))!;

    /// <summary>
    ///   Looks up a localized string similar to O e-mail é obrigatório.
    /// </summary>
    public static string Usuario_Email_Obrigatorio
        => ResourceManager.GetString(nameof(Usuario_Email_Obrigatorio))!;

    /// <summary>
    ///   Looks up a localized string similar to O e-mail informado não é válido.
    /// </summary>
    public static string Usuario_Email_Invalido
        => ResourceManager.GetString(nameof(Usuario_Email_Invalido))!;

    /// <summary>
    ///   Looks up a localized string similar to O documento (CPF/CNPJ) é obrigatório.
    /// </summary>
    public static string Usuario_Documento_Obrigatorio
        => ResourceManager.GetString(nameof(Usuario_Documento_Obrigatorio))!;

    /// <summary>
    ///   Looks up a localized string similar to O documento deve ser um CPF ou CNPJ válido.
    /// </summary>
    public static string Usuario_Documento_Invalido
        => ResourceManager.GetString(nameof(Usuario_Documento_Invalido))!;

    /// <summary>
    ///   Looks up a localized string similar to A senha é obrigatória.
    /// </summary>
    public static string Usuario_Senha_Obrigatoria
        => ResourceManager.GetString(nameof(Usuario_Senha_Obrigatoria))!;

    /// <summary>
    ///   Looks up a localized string similar to A senha deve ter pelo menos 8 caracteres.
    /// </summary>
    public static string Usuario_Senha_TamanhoMinimo
        => ResourceManager.GetString(nameof(Usuario_Senha_TamanhoMinimo))!;

    /// <summary>
    ///   Looks up a localized string similar to Já existe um usuário cadastrado com este e-mail.
    /// </summary>
    public static string Usuario_Email_JaCadastrado
        => ResourceManager.GetString(nameof(Usuario_Email_JaCadastrado))!;

    /// <summary>
    ///   Looks up a localized string similar to Já existe um usuário cadastrado com este documento.
    /// </summary>
    public static string Usuario_Documento_JaCadastrado
        => ResourceManager.GetString(nameof(Usuario_Documento_JaCadastrado))!;

    // ── API — títulos HTTP ─────────────────────────────────────────────────

    /// <summary>
    ///   Looks up a localized string similar to Falha de validação.
    /// </summary>
    public static string Titulo_FalhaValidacao
        => ResourceManager.GetString(nameof(Titulo_FalhaValidacao))!;

    /// <summary>
    ///   Looks up a localized string similar to Ocorreu um erro inesperado.
    /// </summary>
    public static string Titulo_ErroInesperado
        => ResourceManager.GetString(nameof(Titulo_ErroInesperado))!;

    /// <summary>
    ///   Looks up a localized string similar to Não autorizado.
    /// </summary>
    public static string Titulo_NaoAutorizado
        => ResourceManager.GetString(nameof(Titulo_NaoAutorizado))!;

    /// <summary>
    ///   Looks up a localized string similar to Não encontrado.
    /// </summary>
    public static string Titulo_NaoEncontrado
        => ResourceManager.GetString(nameof(Titulo_NaoEncontrado))!;

    /// <summary>
    ///   Looks up a localized string similar to Conflito.
    /// </summary>
    public static string Titulo_Conflito
        => ResourceManager.GetString(nameof(Titulo_Conflito))!;
}
