//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voltiq.Exceptions.Resources;

using System;
using System.Reflection;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
public static class ResourceErrorMessages
{
    private static global::System.Resources.ResourceManager? _resourceManager;

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    public static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            _resourceManager ??= new global::System.Resources.ResourceManager(
                "Voltiq.Exceptions.Resources.ResourceErrorMessages",
                typeof(ResourceErrorMessages).Assembly);

            return _resourceManager;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to O e-mail é obrigatório.
    /// </summary>
    public static string EMAIL_OBRIGATORIO
        => ResourceManager.GetString(nameof(EMAIL_OBRIGATORIO))!;

    /// <summary>
    ///   Looks up a localized string similar to '{0}' não é um endereço de e-mail válido.
    /// </summary>
    public static string EMAIL_INVALIDO
        => ResourceManager.GetString(nameof(EMAIL_INVALIDO))!;

    /// <summary>
    ///   Looks up a localized string similar to O documento (CPF/CNPJ) é obrigatório.
    /// </summary>
    public static string DOCUMENTO_OBRIGATORIO
        => ResourceManager.GetString(nameof(DOCUMENTO_OBRIGATORIO))!;

    /// <summary>
    ///   Looks up a localized string similar to O documento deve ser um CPF (11 dígitos) ou CNPJ (14 dígitos) válido.
    /// </summary>
    public static string DOCUMENTO_FORMATO_INVALIDO
        => ResourceManager.GetString(nameof(DOCUMENTO_FORMATO_INVALIDO))!;

    /// <summary>
    ///   Looks up a localized string similar to CPF inválido.
    /// </summary>
    public static string CPF_INVALIDO
        => ResourceManager.GetString(nameof(CPF_INVALIDO))!;

    /// <summary>
    ///   Looks up a localized string similar to CNPJ inválido.
    /// </summary>
    public static string CNPJ_INVALIDO
        => ResourceManager.GetString(nameof(CNPJ_INVALIDO))!;

    /// <summary>
    ///   Looks up a localized string similar to O nome é obrigatório.
    /// </summary>
    public static string NOME_OBRIGATORIO
        => ResourceManager.GetString(nameof(NOME_OBRIGATORIO))!;

    /// <summary>
    ///   Looks up a localized string similar to O hash da senha é obrigatório.
    /// </summary>
    public static string HASH_SENHA_OBRIGATORIO
        => ResourceManager.GetString(nameof(HASH_SENHA_OBRIGATORIO))!;

    /// <summary>
    ///   Looks up a localized string similar to A entidade '{0}' com a chave '{1}' não foi encontrada.
    /// </summary>
    public static string ENTIDADE_NAO_ENCONTRADA
        => ResourceManager.GetString(nameof(ENTIDADE_NAO_ENCONTRADA))!;

    // ── Aplicação — Usuário ────────────────────────────────────────────────

    /// <summary>
    ///   Looks up a localized string similar to O nome é obrigatório.
    /// </summary>
    public static string USUARIO_NOME_OBRIGATORIO
        => ResourceManager.GetString(nameof(USUARIO_NOME_OBRIGATORIO))!;

    /// <summary>
    ///   Looks up a localized string similar to O e-mail é obrigatório.
    /// </summary>
    public static string USUARIO_EMAIL_OBRIGATORIO
        => ResourceManager.GetString(nameof(USUARIO_EMAIL_OBRIGATORIO))!;

    /// <summary>
    ///   Looks up a localized string similar to O e-mail informado não é válido.
    /// </summary>
    public static string USUARIO_EMAIL_INVALIDO
        => ResourceManager.GetString(nameof(USUARIO_EMAIL_INVALIDO))!;

    /// <summary>
    ///   Looks up a localized string similar to O documento (CPF/CNPJ) é obrigatório.
    /// </summary>
    public static string USUARIO_DOCUMENTO_OBRIGATORIO
        => ResourceManager.GetString(nameof(USUARIO_DOCUMENTO_OBRIGATORIO))!;

    /// <summary>
    ///   Looks up a localized string similar to O documento deve ser um CPF ou CNPJ válido.
    /// </summary>
    public static string USUARIO_DOCUMENTO_INVALIDO
        => ResourceManager.GetString(nameof(USUARIO_DOCUMENTO_INVALIDO))!;

    /// <summary>
    ///   Looks up a localized string similar to A senha é obrigatória.
    /// </summary>
    public static string USUARIO_SENHA_OBRIGATORIA
        => ResourceManager.GetString(nameof(USUARIO_SENHA_OBRIGATORIA))!;

    /// <summary>
    ///   Looks up a localized string similar to A senha deve ter pelo menos 8 caracteres.
    /// </summary>
    public static string USUARIO_SENHA_TAMANHO_MINIMO
        => ResourceManager.GetString(nameof(USUARIO_SENHA_TAMANHO_MINIMO))!;

    /// <summary>
    ///   Looks up a localized string similar to Já existe um usuário cadastrado com este e-mail.
    /// </summary>
    public static string USUARIO_EMAIL_JA_CADASTRADO
        => ResourceManager.GetString(nameof(USUARIO_EMAIL_JA_CADASTRADO))!;

    /// <summary>
    ///   Looks up a localized string similar to Já existe um usuário cadastrado com este documento.
    /// </summary>
    public static string USUARIO_DOCUMENTO_JA_CADASTRADO
        => ResourceManager.GetString(nameof(USUARIO_DOCUMENTO_JA_CADASTRADO))!;

    // ── API — títulos HTTP ─────────────────────────────────────────────────

    /// <summary>
    ///   Looks up a localized string similar to Falha de validação.
    /// </summary>
    public static string TITULO_FALHA_VALIDACAO
        => ResourceManager.GetString(nameof(TITULO_FALHA_VALIDACAO))!;

    /// <summary>
    ///   Looks up a localized string similar to Ocorreu um erro inesperado.
    /// </summary>
    public static string TITULO_ERRO_INESPERADO
        => ResourceManager.GetString(nameof(TITULO_ERRO_INESPERADO))!;

    /// <summary>
    ///   Looks up a localized string similar to Não autorizado.
    /// </summary>
    public static string TITULO_NAO_AUTORIZADO
        => ResourceManager.GetString(nameof(TITULO_NAO_AUTORIZADO))!;

    /// <summary>
    ///   Looks up a localized string similar to Não encontrado.
    /// </summary>
    public static string TITULO_NAO_ENCONTRADO
        => ResourceManager.GetString(nameof(TITULO_NAO_ENCONTRADO))!;

    /// <summary>
    ///   Looks up a localized string similar to Conflito.
    /// </summary>
    public static string TITULO_CONFLITO
        => ResourceManager.GetString(nameof(TITULO_CONFLITO))!;
}
