//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voltiq.Exceptions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Voltiq.Exceptions.Resources.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail informado não é válido..
        /// </summary>
        public static string CLIENTE_EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("CLIENTE_EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um cliente cadastrado com este e-mail..
        /// </summary>
        public static string CLIENTE_EMAIL_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("CLIENTE_EMAIL_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail do cliente é obrigatório..
        /// </summary>
        public static string CLIENTE_EMAIL_OBRIGATORIO {
            get {
                return ResourceManager.GetString("CLIENTE_EMAIL_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CEP é obrigatório..
        /// </summary>
        public static string CLIENTE_ENDERECO_CEP_OBRIGATORIO {
            get {
                return ResourceManager.GetString("CLIENTE_ENDERECO_CEP_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cidade é obrigatória..
        /// </summary>
        public static string CLIENTE_ENDERECO_CIDADE_OBRIGATORIA {
            get {
                return ResourceManager.GetString("CLIENTE_ENDERECO_CIDADE_OBRIGATORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estado é obrigatório..
        /// </summary>
        public static string CLIENTE_ENDERECO_ESTADO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("CLIENTE_ENDERECO_ESTADO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O logradouro é obrigatório..
        /// </summary>
        public static string CLIENTE_ENDERECO_LOGRADOURO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("CLIENTE_ENDERECO_LOGRADOURO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número é obrigatório..
        /// </summary>
        public static string CLIENTE_ENDERECO_NUMERO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("CLIENTE_ENDERECO_NUMERO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente não encontrado..
        /// </summary>
        public static string CLIENTE_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("CLIENTE_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do cliente é obrigatório..
        /// </summary>
        public static string CLIENTE_NOME_OBRIGATORIO {
            get {
                return ResourceManager.GetString("CLIENTE_NOME_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone do cliente é obrigatório..
        /// </summary>
        public static string CLIENTE_TELEFONE_OBRIGATORIO {
            get {
                return ResourceManager.GetString("CLIENTE_TELEFONE_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ inválido..
        /// </summary>
        public static string CNPJ_INVALIDO {
            get {
                return ResourceManager.GetString("CNPJ_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF inválido..
        /// </summary>
        public static string CPF_INVALIDO {
            get {
                return ResourceManager.GetString("CPF_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O documento deve ser um CPF (11 dígitos) ou CNPJ (14 dígitos) válido..
        /// </summary>
        public static string DOCUMENTO_FORMATO_INVALIDO {
            get {
                return ResourceManager.GetString("DOCUMENTO_FORMATO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O documento (CPF/CNPJ) é obrigatório..
        /// </summary>
        public static string DOCUMENTO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("DOCUMENTO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; não é um endereço de e-mail válido..
        /// </summary>
        public static string EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é obrigatório..
        /// </summary>
        public static string EMAIL_OBRIGATORIO {
            get {
                return ResourceManager.GetString("EMAIL_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A entidade &apos;{0}&apos; com a chave &apos;{1}&apos; não foi encontrada..
        /// </summary>
        public static string ENTIDADE_NAO_ENCONTRADA {
            get {
                return ResourceManager.GetString("ENTIDADE_NAO_ENCONTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O hash da senha é obrigatório..
        /// </summary>
        public static string HASH_SENHA_OBRIGATORIO {
            get {
                return ResourceManager.GetString("HASH_SENHA_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail e/ou senha inválidos..
        /// </summary>
        public static string LOGIN_CREDENCIAIS_INVALIDAS {
            get {
                return ResourceManager.GetString("LOGIN_CREDENCIAIS_INVALIDAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material não encontrado..
        /// </summary>
        public static string MATERIAL_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("MATERIAL_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do material é obrigatório..
        /// </summary>
        public static string MATERIAL_NOME_OBRIGATORIO {
            get {
                return ResourceManager.GetString("MATERIAL_NOME_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O preço padrão deve ser maior que zero..
        /// </summary>
        public static string MATERIAL_PRECO_INVALIDO {
            get {
                return ResourceManager.GetString("MATERIAL_PRECO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade de medida inválida..
        /// </summary>
        public static string MATERIAL_UNIDADE_INVALIDA {
            get {
                return ResourceManager.GetString("MATERIAL_UNIDADE_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário do material é obrigatório..
        /// </summary>
        public static string MATERIAL_USUARIO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("MATERIAL_USUARIO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório..
        /// </summary>
        public static string NOME_OBRIGATORIO {
            get {
                return ResourceManager.GetString("NOME_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cliente do orçamento é obrigatório..
        /// </summary>
        public static string ORCAMENTO_CLIENTE_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ORCAMENTO_CLIENTE_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O material deve ser nulo para este tipo de item..
        /// </summary>
        public static string ORCAMENTO_ITEM_MATERIAL_ID_DEVE_SER_NULO {
            get {
                return ResourceManager.GetString("ORCAMENTO_ITEM_MATERIAL_ID_DEVE_SER_NULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O material é obrigatório para itens do tipo Material..
        /// </summary>
        public static string ORCAMENTO_ITEM_MATERIAL_ID_OBRIGATORIO_PARA_MATERIAL {
            get {
                return ResourceManager.GetString("ORCAMENTO_ITEM_MATERIAL_ID_OBRIGATORIO_PARA_MATERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do material no item é obrigatório..
        /// </summary>
        public static string ORCAMENTO_ITEM_NOME_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ORCAMENTO_ITEM_NOME_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O preço unitário deve ser maior que zero..
        /// </summary>
        public static string ORCAMENTO_ITEM_PRECO_INVALIDO {
            get {
                return ResourceManager.GetString("ORCAMENTO_ITEM_PRECO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade deve ser maior que zero..
        /// </summary>
        public static string ORCAMENTO_ITEM_QUANTIDADE_INVALIDA {
            get {
                return ResourceManager.GetString("ORCAMENTO_ITEM_QUANTIDADE_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de item do orçamento inválido..
        /// </summary>
        public static string ORCAMENTO_ITEM_TIPO_INVALIDO {
            get {
                return ResourceManager.GetString("ORCAMENTO_ITEM_TIPO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unidade deve ser nula para este tipo de item..
        /// </summary>
        public static string ORCAMENTO_ITEM_UNIDADE_DEVE_SER_NULA {
            get {
                return ResourceManager.GetString("ORCAMENTO_ITEM_UNIDADE_DEVE_SER_NULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unidade é obrigatória para itens do tipo Material..
        /// </summary>
        public static string ORCAMENTO_ITEM_UNIDADE_OBRIGATORIA_PARA_MATERIAL {
            get {
                return ResourceManager.GetString("ORCAMENTO_ITEM_UNIDADE_OBRIGATORIA_PARA_MATERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O orçamento deve conter pelo menos um item..
        /// </summary>
        public static string ORCAMENTO_ITEMS_OBRIGATORIOS {
            get {
                return ResourceManager.GetString("ORCAMENTO_ITEMS_OBRIGATORIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orçamento não encontrado..
        /// </summary>
        public static string ORCAMENTO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("ORCAMENTO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apenas orçamentos em rascunho podem ser editados..
        /// </summary>
        public static string ORCAMENTO_APENAS_RASCUNHO_PODE_SER_EDITADO {
            get {
                return ResourceManager.GetString("ORCAMENTO_APENAS_RASCUNHO_PODE_SER_EDITADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apenas orçamentos em rascunho podem ser finalizados..
        /// </summary>
        public static string ORCAMENTO_APENAS_RASCUNHO_PODE_SER_FINALIZADO {
            get {
                return ResourceManager.GetString("ORCAMENTO_APENAS_RASCUNHO_PODE_SER_FINALIZADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O status atual do orçamento não permite aprovação. Ele deve estar finalizado ou com PDF gerado..
        /// </summary>
        public static string ORCAMENTO_STATUS_INVALIDO_PARA_APROVACAO {
            get {
                return ResourceManager.GetString("ORCAMENTO_STATUS_INVALIDO_PARA_APROVACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O status atual do orçamento não permite rejeição. Ele deve estar finalizado ou com PDF gerado..
        /// </summary>
        public static string ORCAMENTO_STATUS_INVALIDO_PARA_REJEICAO {
            get {
                return ResourceManager.GetString("ORCAMENTO_STATUS_INVALIDO_PARA_REJEICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário do orçamento é obrigatório..
        /// </summary>
        public static string ORCAMENTO_USUARIO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ORCAMENTO_USUARIO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token expirado..
        /// </summary>
        public static string REFRESH_TOKEN_EXPIRADO {
            get {
                return ResourceManager.GetString("REFRESH_TOKEN_EXPIRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token inválido..
        /// </summary>
        public static string REFRESH_TOKEN_INVALIDO {
            get {
                return ResourceManager.GetString("REFRESH_TOKEN_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token não encontrado..
        /// </summary>
        public static string REFRESH_TOKEN_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("REFRESH_TOKEN_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflito.
        /// </summary>
        public static string TITULO_CONFLITO {
            get {
                return ResourceManager.GetString("TITULO_CONFLITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado..
        /// </summary>
        public static string TITULO_ERRO_INESPERADO {
            get {
                return ResourceManager.GetString("TITULO_ERRO_INESPERADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não autorizado.
        /// </summary>
        public static string TITULO_NAO_AUTORIZADO {
            get {
                return ResourceManager.GetString("TITULO_NAO_AUTORIZADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não encontrado.
        /// </summary>
        public static string TITULO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("TITULO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha de validação.
        /// </summary>
        public static string TITULO_VALIDACAO {
            get {
                return ResourceManager.GetString("TITULO_VALIDACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O documento deve ser um CPF ou CNPJ válido..
        /// </summary>
        public static string USUARIO_DOCUMENTO_INVALIDO {
            get {
                return ResourceManager.GetString("USUARIO_DOCUMENTO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um usuário cadastrado com este documento..
        /// </summary>
        public static string USUARIO_DOCUMENTO_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("USUARIO_DOCUMENTO_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O documento (CPF/CNPJ) é obrigatório..
        /// </summary>
        public static string USUARIO_DOCUMENTO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("USUARIO_DOCUMENTO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail informado não é válido..
        /// </summary>
        public static string USUARIO_EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("USUARIO_EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um usuário cadastrado com este e-mail..
        /// </summary>
        public static string USUARIO_EMAIL_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("USUARIO_EMAIL_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é obrigatório..
        /// </summary>
        public static string USUARIO_EMAIL_OBRIGATORIO {
            get {
                return ResourceManager.GetString("USUARIO_EMAIL_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório..
        /// </summary>
        public static string USUARIO_NOME_OBRIGATORIO {
            get {
                return ResourceManager.GetString("USUARIO_NOME_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha é obrigatória..
        /// </summary>
        public static string USUARIO_SENHA_OBRIGATORIA {
            get {
                return ResourceManager.GetString("USUARIO_SENHA_OBRIGATORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve ter pelo menos 8 caracteres..
        /// </summary>
        public static string USUARIO_SENHA_TAMANHO_MINIMO {
            get {
                return ResourceManager.GetString("USUARIO_SENHA_TAMANHO_MINIMO", resourceCulture);
            }
        }
    }
}
